import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:widgetbook_golden_test_core/src/helpers/test_http_overrides.dart';
import 'package:widgetbook_golden_test_core/widgetbook_golden_test_core.dart';

/// Runs the [testBody] within a zoned environment that mocks HTTP requests.
///
/// This is used to handle network images during golden tests by providing
/// a mocked [HttpClient] and overriding [FlutterError.onError] to ignore
/// specific image loading exceptions.
Future<void> goldenTestZoneRunner({
  required Future<void> Function() testBody,
  required WidgetbookGoldenTestsProperties properties,
}) async {
  final previousOnError = FlutterError.onError;
  Object? bodyError;
  await runZonedGuarded<Future<void>>(
    () async {
      await HttpOverrides.runZoned(() async {
        FlutterError.onError = (FlutterErrorDetails details) async {
          // Ignore image loading errors for generated by the mocked http client.
          handleError(details, properties, previousOnError);
        };
        try {
          await testBody();
        } catch (e) {
          bodyError = e;
        } finally {
          FlutterError.onError = previousOnError;
        }
      }, createHttpClient: (_) => createHttpClient(properties));
    },
    (error, stack) {
      var details = FlutterErrorDetails(
        exception: error,
        stack: stack,
        context: ErrorDescription(error.toString()),
      );
      handleError(details, properties, null);
    },
  );

  if (bodyError != null) {
    handleError(
      FlutterErrorDetails(
        exception: bodyError!,
        stack: StackTrace.current,
        context: ErrorDescription(bodyError.toString()),
      ),
      properties,
      null,
    );
  }
}

/// Handles errors occurring during golden tests.
///
/// It ignores [IgnoreNetworkImageException] and forwards other errors to
/// [properties.onTestError] if provided, or the [previousOnError] handler.
@visibleForTesting
void handleError(
  FlutterErrorDetails details,
  WidgetbookGoldenTestsProperties properties,
  Function(FlutterErrorDetails)? previousOnError,
) {
  // Ignore image loading errors for generated by the mocked http client.
  if (details.exception is IgnoreNetworkImageException) {
    return;
  }

  if (properties.onTestError != null) {
    properties.onTestError!(details, previousOnError);
  } else if (previousOnError != null) {
    previousOnError(details);
  } else {
    throw details.exception;
  }
}
