name: widgetbook_golden_test

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    # All packages will be versioned together.
    # We use a group here to ensure they stay in sync.
    versioning:
      - packages/**
    # Use the version as the tag name without a 'v' prefix to match existing process.
    tagPrefix: ''
sdkPath: .fvm/flutter_sdk