name: widgetbook_golden_test_alchemist_example
description: "Example for widgetbook_golden_test_alchemist"
version: 0.0.1
homepage:
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  alchemist: ^0.13.0
  widgetbook: ^3.20.2
  flutter_cache_manager: ^3.4.1
  get_it: ^9.2.1
  widgetbook_samples: any
  widgetbook_golden_test_alchemist: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
