import 'package:flutter/widgets.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_golden_test_core/src/golden_play_action.dart';

/// Enum to define the strategy to merge addons from the builder and the properties.
enum AddonsMergeStrategy {
  /// Overrides all addons with the ones from the builder. This will remove any addons used in the properties.
  overrideAll,

  /// Replaces the addons from the properties with the ones from the builder that match the type (maintaining the order) and inserts any additional addons at the end.
  replaceAndInsertAtEnd,

  /// Replaces the addons from the properties with the ones from the builder that match the type (maintaining the order) and inserts any additional addons at the beginning.
  replaceAndInsertAtBeginning,
}

/// A builder widget that wraps a child widget and provides additional functionality for golden tests
/// generated by widgetbook_golden_test.
///
/// This widget should be used as the top-level [Widget] in the [WidgetbookUseCase] builder to ensure
/// proper functionality. Optionally, a list of [GoldenPlayAction]s can be
/// provided to define custom play actions for the test.
class WidgetbookGoldenTestBuilder extends StatelessWidget {
  /// Optional list of addons to be applied to the golden snapshots by using their default values.
  /// These are only used for the Golden Tests and won't be used in the actual case running in Widgetbook.
  final List<WidgetbookAddon>? addons;

  /// The strategy to merge addons from the builder and the properties.
  final AddonsMergeStrategy addonsMergeStrategy;

  /// The builder function to be used to build the widget to be tested.
  final WidgetBuilder? builder;

  /// The widget to be wrapped and tested.
  @Deprecated('Use builder instead')
  final Widget? child;

  /// Optional constraints to be applied to the widget to be tested.
  final BoxConstraints? constraints;

  /// Optional list of actions to perform during golden tests.
  final List<GoldenPlayAction>? goldenActions;

  /// Optional flag to skip the golden test.
  final bool skip;

  /// Creates a [WidgetbookGoldenTestBuilder].
  ///
  /// [addons] is an optional list of widgetbook addons to be applied to the golden snapshots by using their default values.
  /// [addonsMergeStrategy] is the strategy to merge addons from the builder and the properties.
  /// [builder] is the builder function to be used to build the widget to be tested.
  /// [child] is required and represents the widget under test.
  /// [constraints] is an optional BoxConstraints to be applied to the widget to be tested.
  /// [goldenActions] is an optional list of actions to execute during the test.
  /// [skip] is an optional flag to skip the golden test.
  const WidgetbookGoldenTestBuilder({
    super.key,
    this.addons,
    this.addonsMergeStrategy = AddonsMergeStrategy.replaceAndInsertAtBeginning,
    this.builder,
    @Deprecated('Use builder instead') this.child,
    this.constraints,
    this.goldenActions,
    this.skip = false,
  }) : assert(
         child != null || builder != null,
         'child or builder must be provided',
       );

  @override
  Widget build(BuildContext context) {
    // ignore: deprecated_member_use_from_same_package
    final child = builder?.call(context) ?? this.child!;

    return child;
  }
}
