import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_golden_test/src/golden_play_action.dart';
import 'package:widgetbook_golden_test/src/ignore_network_image_exception.dart';
import 'package:widgetbook_golden_test/src/test_http_overrides.dart';
import 'package:widgetbook_golden_test/src/widget_tester_extension.dart';
import 'package:widgetbook_golden_test/src/widgetbook_golden_test_builder.dart';
import 'package:widgetbook_golden_test/src/widgetbook_golden_tests_properties.dart';

class _BuildContextMock extends Mock implements BuildContext {}

/// Creates and runs a golden test of the given Widgetbook [useCase].
/// The golden snapshot is saved in [goldenSnapshotsOutputPath]
void createGoldenTest(
  WidgetbookUseCase useCase,
  String goldenSnapshotsOutputPath,
  WidgetbookGoldenTestsProperties properties,
) {
  WidgetbookGoldenTestBuilder? goldenTestBuilder;
  final mockContext = _BuildContextMock();
  try {
    final widget = useCase.build(mockContext);
    if (widget is WidgetbookGoldenTestBuilder) {
      goldenTestBuilder = widget;
    }
  } catch (e) {
    // Not a WidgetbookGoldenTestBuilder.
  }

  // Skip the golden test case if it contains the [skip-golden] tag just as a fallback.
  bool shouldSkip =
      (goldenTestBuilder?.skip ?? false) ||
      // ignore: deprecated_member_use_from_same_package
      useCase.name.contains(properties.skipTag);
  // Golden test case of the story.
  testWidgetsGolden(useCase.name, properties, shouldSkip, (widgetTester) async {
    final widgetToTest = await widgetTester.pumpWidgetbookCase(
      properties,
      useCase,
    );

    await expectLater(
      find.byType(widgetToTest.runtimeType).first,
      matchesGoldenFile("$goldenSnapshotsOutputPath/${useCase.name}.png"),
    );
  });

  if (goldenTestBuilder?.goldenActions != null) {
    for (final play in goldenTestBuilder!.goldenActions!) {
      testWidgetsGolden(
        "${useCase.name} - ${play.name}",
        properties,
        shouldSkip,
        (widgetTester) async {
          await validatePlayFunction(
            widgetTester,
            properties,
            useCase,
            play,
            goldenSnapshotsOutputPath,
          );
        },
      );
    }
  }
}

@visibleForTesting
void testWidgetsGolden(
  String description,
  WidgetbookGoldenTestsProperties properties,
  bool skip,
  Future<void> Function(WidgetTester widgetTester) testBody,
) {
  testWidgets(description, (widgetTester) async {
    final previousOnError = FlutterError.onError;
    await runZonedGuarded<Future<void>>(
      () async {
        await HttpOverrides.runZoned(() async {
          FlutterError.onError = (FlutterErrorDetails details) async {
            // Ignore image loading errors for generated by the mocked http client.
            handleError(details, properties, previousOnError);
          };
          try {
            await testBody(widgetTester);
          } finally {
            FlutterError.onError = previousOnError;
          }
        }, createHttpClient: (_) => createHttpClient(properties));
      },
      (error, stack) {
        var details = FlutterErrorDetails(
          exception: error,
          stack: stack,
          context: ErrorDescription(error.toString()),
        );
        handleError(details, properties, null);
      },
    );
  }, skip: skip);
}

Future<void> validatePlayFunction(
  WidgetTester widgetTester,
  WidgetbookGoldenTestsProperties properties,
  WidgetbookUseCase useCase,
  GoldenPlayAction play,
  String goldenSnapshotsOutputPath,
) async {
  final widgetToTest = await widgetTester.pumpWidgetbookCase(
    properties,
    useCase,
  );
  await play.callback(widgetTester, find);
  await widgetTester.pumpAndSettle();
  Finder goldenFinder =
      play.goldenFinder == null
          ? find.byType(widgetToTest.runtimeType).first
          : play.goldenFinder!.call(find);
  await expectLater(
    goldenFinder,
    matchesGoldenFile(
      "$goldenSnapshotsOutputPath/${useCase.name} - ${play.name}.png",
    ),
  );
}

@visibleForTesting
void handleError(
  FlutterErrorDetails details,
  WidgetbookGoldenTestsProperties properties,
  Function(FlutterErrorDetails)? previousOnError,
) {
  // Ignore image loading errors for generated by the mocked http client.
  if (details.exception is IgnoreNetworkImageException) {
    return;
  }

  if (properties.onTestError != null) {
    properties.onTestError!(details, previousOnError);
  } else if (previousOnError != null) {
    previousOnError(details);
  } else {
    throw details.exception;
  }
}
