import 'package:flutter/widgets.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_golden_test/src/golden_play_action.dart';

/// A builder widget that wraps a child widget and provides additional functionality for golden tests
/// generated by widgetbook_golden_test.
///
/// This widget should be used as the top-level [Widget] in the [WidgetbookUseCase] builder to ensure
/// proper functionality. Optionally, a list of [GoldenPlayAction]s can be
/// provided to define custom play actions for the test.
class WidgetbookGoldenTestBuilder extends StatelessWidget {
  /// The widget to be wrapped and tested.
  final Widget child;

  /// Optional list of actions to perform during golden tests.
  final List<GoldenPlayAction>? goldenActions;

  /// Creates a [WidgetbookGoldenTestBuilder].
  ///
  /// [child] is required and represents the widget under test.
  /// [goldenActions] is an optional list of actions to execute during the test.
  const WidgetbookGoldenTestBuilder({
    super.key,
    required this.child,
    this.goldenActions,
  });

  @override
  Widget build(BuildContext context) {
    return child;
  }
}
