import 'package:flutter/widgets.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_golden_test/src/golden_play_action.dart';

/// A builder widget that wraps a child widget and provides additional functionality for golden tests
/// generated by widgetbook_golden_test.
///
/// This widget should be used as the top-level [Widget] in the [WidgetbookUseCase] builder to ensure
/// proper functionality. Optionally, a list of [GoldenPlayAction]s can be
/// provided to define custom play actions for the test.
class WidgetbookGoldenTestBuilder extends StatelessWidget {
  /// The widget to be wrapped and tested.
  @Deprecated('Use builder instead')
  final Widget? child;

  /// The builder function to be used to build the widget to be tested.
  final WidgetBuilder? builder;

  /// Optional list of actions to perform during golden tests.
  final List<GoldenPlayAction>? goldenActions;

  /// Optional flag to skip the golden test.
  final bool skip;

  /// Creates a [WidgetbookGoldenTestBuilder].
  ///
  /// [child] is required and represents the widget under test.
  /// [goldenActions] is an optional list of actions to execute during the test.
  const WidgetbookGoldenTestBuilder({
    super.key,
    @Deprecated('Use builder instead') this.child,
    this.builder,
    this.goldenActions,
    this.skip = false,
  }) : assert(
         child != null || builder != null,
         'child or builder must be provided',
       );

  @override
  Widget build(BuildContext context) {
    // ignore: deprecated_member_use_from_same_package
    return builder?.call(context) ?? child!;
  }
}
